package examenhibernatetres;
// Generated 19-ene-2018 19:38:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AvisosId generated by hbm2java
 */
public class AvisosId  implements java.io.Serializable {


     private String codigoPersona;
     private String codigoEquipo;
     private Date fechainicio;

    public AvisosId() {
    }

    public AvisosId(String codigoPersona, String codigoEquipo, Date fechainicio) {
       this.codigoPersona = codigoPersona;
       this.codigoEquipo = codigoEquipo;
       this.fechainicio = fechainicio;
    }
   
    public String getCodigoPersona() {
        return this.codigoPersona;
    }
    
    public void setCodigoPersona(String codigoPersona) {
        this.codigoPersona = codigoPersona;
    }
    public String getCodigoEquipo() {
        return this.codigoEquipo;
    }
    
    public void setCodigoEquipo(String codigoEquipo) {
        this.codigoEquipo = codigoEquipo;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AvisosId) ) return false;
		 AvisosId castOther = ( AvisosId ) other; 
         
		 return ( (this.getCodigoPersona()==castOther.getCodigoPersona()) || ( this.getCodigoPersona()!=null && castOther.getCodigoPersona()!=null && this.getCodigoPersona().equals(castOther.getCodigoPersona()) ) )
 && ( (this.getCodigoEquipo()==castOther.getCodigoEquipo()) || ( this.getCodigoEquipo()!=null && castOther.getCodigoEquipo()!=null && this.getCodigoEquipo().equals(castOther.getCodigoEquipo()) ) )
 && ( (this.getFechainicio()==castOther.getFechainicio()) || ( this.getFechainicio()!=null && castOther.getFechainicio()!=null && this.getFechainicio().equals(castOther.getFechainicio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodigoPersona() == null ? 0 : this.getCodigoPersona().hashCode() );
         result = 37 * result + ( getCodigoEquipo() == null ? 0 : this.getCodigoEquipo().hashCode() );
         result = 37 * result + ( getFechainicio() == null ? 0 : this.getFechainicio().hashCode() );
         return result;
   }   


}


