package examenhibernatetres;
// Generated 19-ene-2018 19:38:59 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Avisos generated by hbm2java
 */
public class Avisos  implements java.io.Serializable {


     private AvisosId id;
     private Equipos equipos;
     private Personas personas;
     private String descripcion;
     private Date fechafin;
     private String detalles;

    public Avisos() {
    }

	
    public Avisos(AvisosId id, Equipos equipos, Personas personas) {
        this.id = id;
        this.equipos = equipos;
        this.personas = personas;
    }
    public Avisos(AvisosId id, Equipos equipos, Personas personas,
            String descripcion, Date fechafin, String detalles) {
       this.id = id;
       this.equipos = equipos;
       this.personas = personas;
       this.descripcion = descripcion;
       this.fechafin = fechafin;
       this.detalles = detalles;
    }
   
    public AvisosId getId() {
        return this.id;
    }
    
    public void setId(AvisosId id) {
        this.id = id;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public String getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }

    @Override
    public String toString() {
        return "Avisos{" + "id=" + id + ", equipos=" + equipos + 
                ", personas=" + personas + ", descripcion=" + descripcion + 
                ", fechafin=" + fechafin + ", detalles=" + detalles + '}';
    }




}


