package examenhibernatetres;
// Generated 19-ene-2018 19:38:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Personas generated by hbm2java
 */
public class Personas  implements java.io.Serializable {


     private String codigo;
     private String nombre;
     private String pass;
     private String email;
     private Set avisoses = new HashSet(0);

    public Personas() {
    }

	
    public Personas(String codigo) {
        this.codigo = codigo;
    }
    public Personas(String codigo, String nombre, String pass, String email, Set avisoses) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.pass = pass;
       this.email = email;
       this.avisoses = avisoses;
    }
   
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getAvisoses() {
        return this.avisoses;
    }
    
    public void setAvisoses(Set avisoses) {
        this.avisoses = avisoses;
    }




}


